{:wrap-reload false
 :db-host "localhost"
 :db-user nil
 :db-pwd nil
 :host "smtp.googlemail.com"
 :user "team@4clojure.com"
 :problem-submission true
 :advanced-user-count 50
 :pass ""
 :repo-url "https://github.com/4clojure/4clojure"
 :golfing-active true}
