{:wrap-reload false
 :db-host "localhost"
 :db-user nil
 :db-pwd nil
 :host "smtp.googlemail.com"
 :user "team@4clojure.com"
 :problem-submission false
 :advanced-user-count 50
 :pass ""
 :golfing-active true}
